# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 'stable'
        cache: false

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v3.7.0

    - name: Run Gosec Security Scanner
      uses: securego/gosec@master
      with:
        args: ./...

    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/node@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./... -coverprofile=./coverage.out

    - name: Coverage
      uses: vladopajic/go-test-coverage@v2
      with:
        # Configure action by specifying input parameters individually (option 2)
        profile: coverage.out
        local-prefix: github.com/Jh123x/go-validate
        threshold-file: 80
        threshold-package: 80
        threshold-total: 95